### ISSUE TITLE
feat request

### ISSUE THREAD

**Issue by ahmedu007** [joefazz/react-native-web-starter#10]
Hello, 

This starter pack works great. Thankyou. Just wondering if there is a chance to add another branch that makes it easy to install RN dependencies. I've been looking through it for days now and struggling to find a solution.

Thankyou

**Comment by joefazz** [comment]
Hi, thanks for the kind words, what do you mean easy to install RN dependencies? Do you mean that doesn't use Expo for the RN side so you can run react-native link?

**Comment by ahmedu007** [comment]
Im sorry didn't see the earlier notification. I meant to say was when we install any RN dependency it doesn't work on the web, probably because they're not transpiled. I'm sure we hacked something to make it work on the web but if only there is a cleaner way

**Comment by joefazz** [comment]
I guess it depends on the kind of dependency. So long as the dependency is just JavaScript it should always work, for native extensions, you can't really do that anyway because of Expo. This is an issue you'd probably be better off reporting to react-native-web directly as that's where the interopability matters, this is just a jumping off point. If you do find out there's a config that makes this easier though, do comment on this and I'll add it as a branch option.
