### ISSUE TITLE
Invalid value for prop `component` on <a> tag.

### ISSUE THREAD

**Issue by axhamre** [joefazz/react-native-web-starter#7]
Running the branch `navigation-react-router` - I'm getting this error when running in browser (`yarn web`):

`Invalid value for prop `component` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior`

I guess it's related to this line: 

`<Link to={'/one'} component={TouchableOpacity} >`

**Comment by joefazz** [comment]
You're right this is an error. It's because `react-router-dom` doesn't have a component prop but `react-router-native` expects one. You can fix it by seperating the code using the `Platform` api. I'm going to leave it for now because it's not actually a problem with the template it's a problem with the demo code which is deleted anyway.
